"""
utils/stock_list.py
-------------------
Comprehensive Nifty 500 stock list for the FinTemporal RAG stock selector.

Each entry is formatted as:
    "TICKER.NS - Full Company Name"

so Streamlit's native selectbox search can match on EITHER the ticker symbol
OR any word in the company name.

The sentinel at the bottom of the list triggers the custom-ticker text input.
"""

NIFTY_500_STOCKS: list[str] = [
    "RELIANCE.NS - Reliance Industries Ltd.",
    "BHARTIARTL.NS - Bharti Airtel Ltd.",
    "HDFCBANK.NS - HDFC Bank Ltd.",
    "ICICIBANK.NS - ICICI Bank Ltd.",
    "SBIN.NS - State Bank of India",
    "TCS.NS - Tata Consultancy Services Ltd.",
    "BAJFINANCE.NS - Bajaj Finance Ltd.",
    "LT.NS - Larsen & Toubro Ltd.",
    "HINDUNILVR.NS - Hindustan Unilever Ltd.",
    "INFY.NS - Infosys Ltd.",
    "SUNPHARMA.NS - Sun Pharmaceutical Industries Ltd.",
    "MARUTI.NS - Maruti Suzuki India Ltd.",
    "TITAN.NS - Titan Company Ltd.",
    "M&M.NS - Mahindra & Mahindra Ltd.",
    "ADANIPOWER.NS - Adani Power Ltd.",
    "KOTAKBANK.NS - Kotak Mahindra Bank Ltd.",
    "ADANIPORTS.NS - Adani Ports and Special Economic Zone Ltd.",
    "AXISBANK.NS - Axis Bank Ltd.",
    "HCLTECH.NS - HCL Technologies Ltd.",
    "ULTRACEMCO.NS - UltraTech Cement Ltd.",
    "ITC.NS - ITC Ltd.",
    "NTPC.NS - NTPC Ltd.",
    "BAJAJFINSV.NS - Bajaj Finserv Ltd.",
    "HAL.NS - Hindustan Aeronautics Ltd.",
    "JSWSTEEL.NS - JSW Steel Ltd.",
    "BAJAJ-AUTO.NS - Bajaj Auto Ltd.",
    "ONGC.NS - Oil & Natural Gas Corporation Ltd.",
    "NESTLEIND.NS - Nestle India Ltd.",
    "BEL.NS - Bharat Electronics Ltd.",
    "ASIANPAINT.NS - Asian Paints Ltd.",
    "DMART.NS - Avenue Supermarts Ltd.",
    "COALINDIA.NS - Coal India Ltd.",
    "POWERGRID.NS - Power Grid Corporation of India Ltd.",
    "HINDZINC.NS - Hindustan Zinc Ltd.",
    "TATASTEEL.NS - Tata Steel Ltd.",
    "ADANIGREEN.NS - Adani Green Energy Ltd.",
    "HINDALCO.NS - Hindalco Industries Ltd.",
    "DIVISLAB.NS - Divi's Laboratories Ltd.",
    "EICHERMOT.NS - Eicher Motors Ltd.",
    "GRASIM.NS - Grasim Industries Ltd.",
    "TVSMOTOR.NS - TVS Motor Company Ltd.",
    "INDIGO.NS - InterGlobe Aviation Ltd.",
    "IOC.NS - Indian Oil Corporation Ltd.",
    "WIPRO.NS - Wipro Ltd.",
    "TORNTPHARM.NS - Torrent Pharmaceuticals Ltd.",
    "SBILIFE.NS - SBI Life Insurance Company Ltd.",
    "PIDILITIND.NS - Pidilite Industries Ltd.",
    "SOLARINDS.NS - Solar Industries India Ltd.",
    "CHOLAFIN.NS - Cholamandalam Investment and Finance Company Ltd.",
    "TRENT.NS - Trent Ltd.",
    "MOTHERSUMI.NS - Motherson Sumi Systems Ltd.",
    "DLF.NS - DLF Ltd.",
    "TATAMOTORS.NS - Tata Motors Ltd.",
    "VBL.NS - Varun Beverages Ltd.",
    "CUMMINSIND.NS - Cummins India Ltd.",
    "TECHM.NS - Tech Mahindra Ltd.",
    "BHEL.NS - Bharat Heavy Electricals Ltd.",
    "BSE.NS - BSE Ltd.",
    "SIEMENS.NS - Siemens Ltd.",
    "BPCL.NS - Bharat Petroleum Corporation Ltd.",
    "POLYCAB.NS - Polycab India Ltd.",
    "IDEA.NS - Vodafone Idea Ltd.",
    "PFC.NS - Power Finance Corporation Ltd.",
    "UNIONBANK.NS - Union Bank of India",
    "PNB.NS - Punjab National Bank",
    "BRITANNIA.NS - Britannia Industries Ltd.",
    "BAJAJHLDNG.NS - Bajaj Holdings & Investment Ltd.",
    "APOLLOHOSP.NS - Apollo Hospitals Enterprise Ltd.",
    "BANKBARODA.NS - Bank of Baroda",
    "BOSCHLTD.NS - Bosch Ltd.",
    "TATAPOWER.NS - Tata Power Co. Ltd.",
    "CIPLA.NS - Cipla Ltd.",
    "HDFCLIFE.NS - HDFC Life Insurance Company Ltd.",
    "CANBK.NS - Canara Bank",
    "MUTHOOTFIN.NS - Muthoot Finance Ltd.",
    "GAIL.NS - GAIL (India) Ltd.",
    "INDIANB.NS - Indian Bank",
    "ABCAPITAL.NS - Aditya Birla Capital Ltd.",
    "JINDALSTEL.NS - Jindal Steel & Power Ltd.",
    "HEROMOTOCO.NS - Hero MotoCorp Ltd.",
    "MARICO.NS - Marico Ltd.",
    "CADILAHC.NS - Cadila Healthcare Ltd.",
    "LUPIN.NS - Lupin Ltd.",
    "GODREJCP.NS - Godrej Consumer Products Ltd.",
    "AMBUJACEM.NS - Ambuja Cements Ltd.",
    "HDFCAMC.NS - HDFC Asset Management Company Ltd.",
    "MCDOWELL-N.NS - United Spirits Ltd.",
    "VEDL.NS - Vedanta Ltd.",
    "TATACONSUM.NS - Tata Consumer Products Ltd.",
    "BHARATFORG.NS - Bharat Forge Ltd.",
    "INDHOTEL.NS - Indian Hotels Co. Ltd.",
    "JSWENERGY.NS - JSW Energy Ltd.",
    "ASHOKLEY.NS - Ashok Leyland Ltd.",
    "LAURUSLABS.NS - Laurus Labs Ltd.",
    "SHREECEM.NS - Shree Cement Ltd.",
    "RECLTD.NS - REC Ltd.",
    "DRREDDY.NS - Dr. Reddy's Laboratories Ltd.",
    "AUROPHARMA.NS - Aurobindo Pharma Ltd.",
    "IDBI.NS - IDBI Bank Ltd.",
    "FEDERALBNK.NS - Federal Bank Ltd.",
    "DIXON.NS - Dixon Technologies (India) Ltd.",
    "PERSISTENT.NS - Persistent Systems Ltd.",
    "HINDPETRO.NS - Hindustan Petroleum Corporation Ltd.",
    "ICICIGI.NS - ICICI Lombard General Insurance Company Ltd.",
    "HAVELLS.NS - Havells India Ltd.",
    "NAUKRI.NS - Info Edge (India) Ltd.",
    "INDUSINDBK.NS - IndusInd Bank Ltd.",
    "AUBANK.NS - AU Small Finance Bank Ltd.",
    "NHPC.NS - NHPC Ltd.",
    "SRF.NS - SRF Ltd.",
    "NMDC.NS - NMDC Ltd.",
    "ICICIPRULI.NS - ICICI Prudential Life Insurance Company Ltd.",
    "IDFCFIRSTB.NS - IDFC First Bank Ltd.",
    "DABUR.NS - Dabur India Ltd.",
    "SAIL.NS - Steel Authority of India Ltd.",
    "OIL.NS - Oil India Ltd.",
    "YESBANK.NS - Yes Bank Ltd.",
    "FORTIS.NS - Fortis Healthcare Ltd.",
    "NATIONALUM.NS - National Aluminium Co. Ltd.",
    "BIOCON.NS - Biocon Ltd.",
    "PHOENIXLTD.NS - Phoenix Mills Ltd.",
    "PRESTIGE.NS - Prestige Estates Projects Ltd.",
    "ALKEM.NS - Alkem Laboratories Ltd.",
    "TORNTPOWER.NS - Torrent Power Ltd.",
    "MCX.NS - Multi Commodity Exchange of India Ltd.",
    "SUZLON.NS - Suzlon Energy Ltd.",
    "OBEROIRLTY.NS - Oberoi Realty Ltd.",
    "IOB.NS - Indian Overseas Bank",
    "BANKINDIA.NS - Bank of India",
    "SCHAEFFLER.NS - Schaeffler India Ltd.",
    "GLENMARK.NS - Glenmark Pharmaceuticals Ltd.",
    "GODREJPROP.NS - Godrej Properties Ltd.",
    "GICRE.NS - General Insurance Corporation of India",
    "BERGEPAINT.NS - Berger Paints India Ltd.",
    "COROMANDEL.NS - Coromandel International Ltd.",
    "JSL.NS - Jindal Stainless Ltd.",
    "MAHABANK.NS - Bank of Maharashtra.",
    "RADICO.NS - Radico Khaitan Ltd",
    "RBLBANK.NS - RBL Bank Ltd.",
    "ABBOTINDIA.NS - Abbott India Ltd.",
    "MRF.NS - MRF Ltd.",
    "COLPAL.NS - Colgate Palmolive (India) Ltd.",
    "APLAPOLLO.NS - APL Apollo Tubes Ltd.",
    "TIINDIA.NS - Tube Investments of India Ltd.",
    "MOTILALOFS.NS - Motilal Oswal Financial Services Ltd.",
    "KEI.NS - KEI Industries Ltd.",
    "MFSL.NS - Max Financial Services Ltd.",
    "HINDCOPPER.NS - Hindustan Copper Ltd.",
    "UPL.NS - UPL Ltd.",
    "BALKRISIND.NS - Balkrishna Industries Ltd.",
    "MPHASIS.NS - MphasiS Ltd.",
    "THERMAX.NS - Thermax Ltd.",
    "BDL.NS - Bharat Dynamics Ltd.",
    "IPCALAB.NS - Ipca Laboratories Ltd.",
    "PAGEIND.NS - Page Industries Ltd.",
    "SUPREMEIND.NS - Supreme Industries Ltd.",
    "AIAENG.NS - AIA Engineering Ltd.",
    "VOLTAS.NS - Voltas Ltd.",
    "PIIND.NS - PI Industries Ltd.",
    "JKCEMENT.NS - J.K. Cement Ltd.",
    "PETRONET.NS - Petronet LNG Ltd.",
    "NLCINDIA.NS - NLC India Ltd.",
    "ENDURANCE.NS - Endurance Technologies Ltd.",
    "HUDCO.NS - Housing & Urban Development Corporation Ltd.",
    "3MINDIA.NS - 3M India Ltd.",
    "EXIDEIND.NS - Exide Industries Ltd.",
    "CONCOR.NS - Container Corporation of India Ltd.",
    "NH.NS - Narayana Hrudayalaya Ltd.",
    "ASTRAL.NS - Astral Poly Technik Ltd.",
    "LTTS.NS - L&T Technology Services Ltd.",
    "COCHINSHIP.NS - Cochin Shipyard Ltd.",
    "UBL.NS - United Breweries Ltd.",
    "HEXAWARE.NS - Hexaware Technologies Ltd.",
    "DALBHARAT.NS - Dalmia Bharat Ltd.",
    "BLUESTARCO.NS - Blue Star Ltd.",
    "ESCORTS.NS - Escorts Ltd.",
    "HONAUT.NS - Honeywell Automation India Ltd.",
    "TATAINVEST.NS - Tata Investment Corporation Ltd.",
    "CRISIL.NS - CRISIL Ltd.",
    "KARURVYSYA.NS - Karur Vysya Bank Ltd.",
    "JUBLFOOD.NS - Jubilant Foodworks Ltd.",
    "LALPATHLAB.NS - Dr. Lal Path Labs Ltd.",
    "GUJGASLTD.NS - Gujarat Gas Ltd.",
    "NIACL.NS - The New India Assurance Company Ltd.",
    "CENTRALBK.NS - Central Bank of India",
    "LICHSGFIN.NS - LIC Housing Finance Ltd.",
    "APOLLOTYRE.NS - Apollo Tyres Ltd.",
    "CDSL.NS - Central Depository Services (India) Ltd.",
    "PGHH.NS - Procter & Gamble Hygiene & Health Care Ltd.",
    "BANDHANBNK.NS - Bandhan Bank Ltd.",
    "PEL.NS - Piramal Enterprises Ltd.",
    "REDINGTON.NS - Redington (India) Ltd.",
    "SJVN.NS - SJVN Ltd.",
    "ITI.NS - ITI Ltd.",
    "AMBER.NS - Amber Enterprises India Ltd.",
    "ACC.NS - ACC Ltd.",
    "IIFL.NS - IIFL Finance Ltd.",
    "NBCC.NS - NBCC (India) Ltd.",
    "TIMKEN.NS - Timken India Ltd.",
    "DEEPAKNTR.NS - Deepak Nitrite Ltd.",
    "ASAHIINDIA.NS - Asahi India Glass Ltd.",
    "TATAELXSI.NS - Tata Elxsi Ltd.",
    "GRINDWELL.NS - Grindwell Norton Ltd.",
    "KALPATPOWR.NS - Kalpataru Power Transmission Ltd.",
    "RAMCOCEM.NS - The Ramco Cements Ltd.",
    "IGL.NS - Indraprastha Gas Ltd.",
    "GRANULES.NS - Granules India Ltd.",
    "CARBORUNIV.NS - Carborundum Universal Ltd.",
    "EIHOTEL.NS - EIH Ltd.",
    "HATSUN.NS - Hatsun Agro Product Ltd.",
    "CUB.NS - City Union Bank Ltd.",
    "ATUL.NS - Atul Ltd.",
    "SUNTV.NS - Sun TV Network Ltd.",
    "CHENNPETRO.NS - Chennai Petroleum Corporation Ltd.",
    "BAYERCROP.NS - Bayer Cropscience Ltd.",
    "CASTROLIND.NS - Castrol India Ltd.",
    "KAJARIACER.NS - Kajaria Ceramics Ltd.",
    "GMDCLTD.NS - Gujarat Mineral Development Corporation Ltd.",
    "ELGIEQUIP.NS - Elgi Equipments Ltd.",
    "CHALET.NS - Chalet Hotels Ltd.",
    "CHAMBLFERT.NS - Chambal Fertilizers & Chemicals Ltd.",
    "WELSPUNIND.NS - Welspun India Ltd.",
    "ECLERX.NS - eClerx Services Ltd.",
    "AARTIIND.NS - Aarti Industries Ltd.",
    "EMAMILTD.NS - Emami Ltd.",
    "BASF.NS - BASF India Ltd.",
    "CROMPTON.NS - Crompton Greaves Consumer Electricals Ltd.",
    "CENTURYPLY.NS - Century Plyboards (India) Ltd.",
    "KANSAINER.NS - Kansai Nerolac Paints Ltd.",
    "KPITTECH.NS - KPIT Technologies Ltd.",
    "RATNAMANI.NS - Ratnamani Metals & Tubes Ltd.",
    "NATCOPHARM.NS - NATCO Pharma Ltd.",
    "SYNGENE.NS - Syngene International Ltd.",
    "APLLTD.NS - Alembic Pharmaceuticals Ltd.",
    "DCMSHRIRAM.NS - DCM Shriram Ltd.",
    "FINCABLES.NS - Finolex Cables Ltd.",
    "FINEORG.NS - Fine Organic Industries Ltd.",
    "CEATLTD.NS - Ceat Ltd.",
    "EIDPARRY.NS - E.I.D. Parry (India) Ltd.",
    "BEML.NS - BEML Ltd.",
    "GRAPHITE.NS - Graphite India Ltd.",
    "VGUARD.NS - V-Guard Industries Ltd.",
    "ENGINERSIN.NS - Engineers India Ltd.",
    "HEG.NS - H.E.G. Ltd.",
    "TRIDENT.NS - Trident Ltd.",
    "KEC.NS - Kec International Ltd.",
    "BLUEDART.NS - Blue Dart Express Ltd.",
    "WABAG.NS - Va Tech Wabag Ltd.",
    "SOUTHBANK.NS - South Indian Bank Ltd.",
    "IEX.NS - Indian Energy Exchange Ltd.",
    "ZENSARTECH.NS - Zensar Technolgies Ltd.",
    "KTKBANK.NS - Karnataka Bank Ltd.",
    "EDELWEISS.NS - Edelweiss Financial Services Ltd.",
    "MGL.NS - Mahanagar Gas Ltd.",
    "VARROC.NS - Varroc Engineering Ltd.",
    "RITES.NS - RITES Ltd.",
    "AAVAS.NS - Aavas Financiers Ltd.",
    "INDIAMART.NS - Indiamart Intermesh Ltd.",
    "BBTC.NS - Bombay Burmah Trading Corporation Ltd.",
    "RELAXO.NS - Relaxo Footwears Ltd.",
    "FINPIPE.NS - Finolex Industries Ltd.",
    "WHIRLPOOL.NS - Whirlpool India Ltd.",
    "TIMETECHNO.NS - Time Technoplast Ltd.",
    "RPOWER.NS - Reliance Power Ltd.",
    "MMTC.NS - MMTC Ltd.",
    "BATAINDIA.NS - Bata India Ltd.",
    "ZEEL.NS - Zee Entertainment Enterprises Ltd.",
    "NCC.NS - NCC Ltd.",
    "CYIENT.NS - Cyient Ltd.",
    "STAR.NS - Strides Pharma Science Ltd.",
    "SUDARSCHEM.NS - Sudarshan Chemical Industries Ltd.",
    "SFL.NS - Sheela Foam Ltd.",
    "RAIN.NS - Rain Industries Ltd",
    "CERA.NS - Cera Sanitaryware Ltd",
    "MIDHANI.NS - Mishra Dhatu Nigam Ltd.",
    "SANOFI.NS - Sanofi India Ltd.",
    "ABFRL.NS - Aditya Birla Fashion and Retail Ltd.",
    "SKFINDIA.NS - SKF India Ltd.",
    "SUPRAJIT.NS - Suprajit Engineering Ltd.",
    "GALAXYSURF.NS - Galaxy Surfactants Ltd.",
    "SPARC.NS - Sun Pharma Advanced Research Company Ltd.",
    "RCF.NS - Rashtriya Chemicals & Fertilizers Ltd.",
    "JKPAPER.NS - JK Paper Ltd.",
    "FDC.NS - FDC Ltd.",
    "ITDC.NS - India Tourism Development Corporation Ltd.",
    "PTC.NS - PTC India Ltd.",
    "IFBIND.NS - IFB Industries Ltd.",
    "GULFOILLUB.NS - Gulf Oil Lubricants India Ltd.",
    "PRAJIND.NS - Praj Industries Ltd.",
    "MOIL.NS - MOIL Ltd.",
    "BLISSGVS.NS - Bliss GVS Pharma Ltd.",
    "CARERATING.NS - CARE Ratings Ltd.",
    "GUJALKALI.NS - Gujarat Alkalies & Chemicals Ltd.",
    "VRLLOG.NS - VRL Logistics Ltd.",
    "QUESS.NS - Quess Corp Ltd.",
    "NETWORK18.NS - Network18 Media & Investments Ltd.",
    "SUNTECK.NS - Sunteck Realty Ltd.",
    "SYMPHONY.NS - Symphony Ltd.",
    "VIPIND.NS - V.I.P. Industries Ltd.",
    "RAYMOND.NS - Raymond Ltd.",
    "VAIBHAVGBL.NS - Vaibhav Global Ltd.",
    "MAHLOG.NS - Mahindra Logistics Ltd.",
    "JCHAC.NS - Johnson Controls - Hitachi Air Conditioning India Ltd.",
    "BAJAJELEC.NS - Bajaj Electricals Ltd",
    "KSCL.NS - Kaveri Seed Company Ltd.",
    "KNRCON.NS - KNR Constructions Ltd.",
    "NFL.NS - National Fertilizers Ltd.",
    "HEIDELBERG.NS - HeidelbergCement India Ltd.",
    "ASHOKA.NS - Ashoka Buildcon Ltd.",
    "ORIENTCEM.NS - Orient Cement Ltd.",
    "PARAGMILK.NS - Parag Milk Foods Ltd.",
    "RELINFRA.NS - Reliance Infrastructure Ltd.",
    "FMGOETZE.NS - Federal-Mogul Goetze (India) Ltd.",
    "NILKAMAL.NS - Nilkamal Ltd.",
    "GEPIL.NS - GE Power India Ltd.",
    "ADANIGAS.NS - Adani Gas Ltd.",
    "ADANITRANS.NS - Adani Transmission Ltd.",
    "ADVENZYMES.NS - Advanced Enzyme Tech Ltd.",
    "AEGISCHEM.NS - Aegis Logistics Ltd.",
    "AFFLE.NS - Affle (India) Ltd.",
    "AJANTPHARM.NS - Ajanta Pharmaceuticals Ltd.",
    "AKZOINDIA.NS - Akzo Nobel India Ltd.",
    "ALLCARGO.NS - Allcargo Logistics Ltd.",
    "AMARAJABAT.NS - Amara Raja Batteries Ltd.",
    "ARVINDFASN.NS - Arvind Fashions Ltd.",
    "ASTERDM.NS - Aster DM Healthcare Ltd.",
    "ASTRAZEN.NS - AstraZenca Pharma India Ltd.",
    "AVANTIFEED.NS - Avanti Feeds Ltd.",
    "BAJAJCON.NS - Bajaj Consumer Care Ltd.",
    "BALMLAWRIE.NS - Balmer Lawrie & Co. Ltd.",
    "BALRAMCHIN.NS - Balrampur Chini Mills Ltd.",
    "BIRLACORPN.NS - Birla Corporation Ltd.",
    "BOMDYEING.NS - Bombay Dyeing & Manufacturing Co. Ltd.",
    "BRIGADE.NS - Brigade Enterprises Ltd.",
    "BSOFT.NS - Birlasoft Ltd.",
    "CANFINHOME.NS - Can Fin Homes Ltd.",
    "CAPLIPOINT.NS - Caplin Point Laboratories Ltd.",
    "CCL.NS - CCL Products (I) Ltd.",
    "CESC.NS - CESC Ltd.",
    "CGCL.NS - Capri Global Capital Ltd.",
    "CHOLAHLDNG.NS - Cholamandalam Financial Holdings Ltd.",
    "CREDITACC.NS - CreditAccess Grameen Ltd.",
    "DBCORP.NS - D.B.Corp Ltd.",
    "DBL.NS - Dilip Buildcon Ltd.",
    "DCAL.NS - Dishman Carbogen Amcis Ltd.",
    "DCBBANK.NS - DCB Bank Ltd.",
    "DELTACORP.NS - Delta Corp Ltd.",
    "DHFL.NS - Dewan Housing Finance Corporation Ltd.",
    "DISHTV.NS - Dish TV India Ltd.",
    "EQUITAS.NS - Equitas Holdings Ltd.",
    "ERIS.NS - Eris Lifesciences Ltd.",
    "ESSELPACK.NS - Essel Propack Ltd.",
    "FCONSUMER.NS - Future Consumer Ltd.",
    "FLFL.NS - Future Lifestyle Fashions Ltd.",
    "FRETAIL.NS - Future Retail Ltd.",
    "FSL.NS - Firstsource Solutions Ltd.",
    "GARFIBRES.NS - Garware Technical Fibres Ltd.",
    "GAYAPROJ.NS - Gayatri Projects Ltd.",
    "GESHIP.NS - Great Eastern Shipping Co. Ltd.",
    "GET&D.NS - GE T&D India Ltd.",
    "GHCL.NS - GHCL Ltd.",
    "GILLETTE.NS - Gillette India Ltd.",
    "GLAXO.NS - Glaxosmithkline Pharmaceuticals Ltd.",
    "GMRINFRA.NS - GMR Infrastructure Ltd.",
    "GNFC.NS - Gujarat Narmada Valley Fertilizers and Chemicals Ltd.",
    "GODFRYPHLP.NS - Godfrey Phillips India Ltd.",
    "GODREJAGRO.NS - Godrej Agrovet Ltd.",
    "GODREJIND.NS - Godrej Industries Ltd.",
    "GPPL.NS - Gujarat Pipavav Port Ltd.",
    "GREAVESCOT.NS - Greaves Cotton Ltd.",
    "GSFC.NS - Gujarat State Fertilizers & Chemicals Ltd.",
    "GSPL.NS - Gujarat State Petronet Ltd.",
    "HDFC.NS - Housing Development Finance Corporation Ltd.",
    "HERITGFOOD.NS - Heritage Foods Ltd.",
    "HFCL.NS - HFCL Ltd.",
    "HIMATSEIDE.NS - Himatsingka Seide Ltd.",
    "HSCL.NS - Himadri Speciality Chemical Ltd.",
    "IBREALEST.NS - Indiabulls Real Estate Ltd.",
    "IBULHSGFIN.NS - Indiabulls Housing Finance Ltd.",
    "IBULISL.NS - Indiabulls Integrated Services Ltd.",
    "IBVENTURES.NS - Indiabulls Ventures Ltd.",
    "ICRA.NS - ICRA Ltd.",
    "IDFC.NS - IDFC Ltd.",
    "IFCI.NS - IFCI Ltd.",
    "INDIACEM.NS - India Cements Ltd.",
    "INDOSTAR.NS - IndoStar Capital Finance Ltd.",
    "INFIBEAM.NS - Infibeam Avenues Ltd.",
    "INFRATEL.NS - Bharti Infratel Ltd.",
    "INOXLEISUR.NS - Inox Leisure Ltd.",
    "INTELLECT.NS - Intellect Design Arena Ltd.",
    "IRB.NS - IRB Infrastructure Developers Ltd.",
    "IRCON.NS - IRCON International Ltd.",
    "ISEC.NS - ICICI Securities Ltd.",
    "ITDCEM.NS - ITD Cementation India Ltd.",
    "J&KBANK.NS - Jammu & Kashmir Bank Ltd.",
    "JAGRAN.NS - Jagran Prakashan Ltd.",
    "JAICORPLTD.NS - Jai Corp Ltd.",
    "JAMNAAUTO.NS - Jamna Auto Industries Ltd.",
    "JBCHEPHARM.NS - J.B. Chemicals & Pharmaceuticals Ltd.",
    "JINDALSAW.NS - Jindal Saw Ltd.",
    "JISLJALEQS.NS - Jain Irrigation Systems Ltd.",
    "JKLAKSHMI.NS - JK Lakshmi Cement Ltd.",
    "JKTYRE.NS - JK Tyre & Industries Ltd.",
    "JMFINANCIL.NS - JM Financial Ltd.",
    "JSLHISAR.NS - Jindal Stainless (Hisar) Ltd.",
    "JUBILANT.NS - Jubilant Life Sciences Ltd.",
    "JUSTDIAL.NS - Justdial Ltd.",
    "JYOTHYLAB.NS - Jyothy Labs Ltd.",
    "KENNAMET.NS - Kennametal India Ltd.",
    "KIRLOSENG.NS - Kirloskar Oil Eng Ltd.",
    "KOLTEPATIL.NS - Kolte-Patil Developers Ltd.",
    "KPRMILL.NS - K.P.R. Mill Ltd.",
    "KRBL.NS - KRBL Ltd.",
    "L&TFH.NS - L&T Finance Holdings Ltd.",
    "LAKSHVILAS.NS - Lakshmi Vilas Bank Ltd.",
    "LAXMIMACH.NS - Lakshmi Machine Works Ltd.",
    "LEMONTREE.NS - Lemon Tree Hotels Ltd.",
    "LINDEINDIA.NS - Linde India Ltd.",
    "LTI.NS - Larsen & Toubro Infotech Ltd.",
    "LUXIND.NS - Lux Industries Ltd.",
    "M&MFIN.NS - Mahindra & Mahindra Financial Services Ltd.",
    "MAGMA.NS - Magma Fincorp Ltd.",
    "MAHINDCIE.NS - Mahindra CIE Automotive Ltd.",
    "MAHSCOOTER.NS - Maharashtra Scooters Ltd.",
    "MAHSEAMLES.NS - Maharashtra Seamless Ltd.",
    "MANAPPURAM.NS - Manappuram Finance Ltd.",
    "MASFIN.NS - MAS Financial Services Ltd.",
    "METROPOLIS.NS - Metropolis Healthcare Ltd.",
    "MHRIL.NS - Mahindra Holidays & Resorts India Ltd.",
    "MINDACORP.NS - Minda Corporation Ltd.",
    "MINDAIND.NS - Minda Industries Ltd.",
    "MINDTREE.NS - MindTree Ltd.",
    "MRPL.NS - Mangalore Refinery & Petrochemicals Ltd.",
    "NAM-INDIA.NS - Nippon Life India Asset Management Ltd.",
    "NAVINFLUOR.NS - Navin Fluorine International Ltd.",
    "NBVENTURES.NS - Nava Bharat Ventures Ltd.",
    "NESCO.NS - NESCO Ltd.",
    "NIITTECH.NS - NIIT Technologies Ltd.",
    "OFSS.NS - Oracle Financial Services Software Ltd.",
    "OMAXE.NS - Omaxe Ltd.",
    "ORIENTELEC.NS - Orient Electric Ltd.",
    "ORIENTREF.NS - Orient Refractories Ltd.",
    "PCJEWELLER.NS - PC Jeweller Ltd.",
    "PFIZER.NS - Pfizer Ltd.",
    "PGHL.NS - Procter & Gamble Health Ltd.",
    "PHILIPCARB.NS - Phillips Carbon Black Ltd.",
    "PNBHOUSING.NS - PNB Housing Finance Ltd.",
    "PNCINFRA.NS - PNC Infratech Ltd.",
    "PRSMJOHNSN.NS - Prism Johnson Ltd.",
    "PVR.NS - PVR Ltd.",
    "RAJESHEXPO.NS - Rajesh Exports Ltd.",
    "RALLIS.NS - Rallis India Ltd.",
    "RELCAPITAL.NS - Reliance Capital Ltd.",
    "RENUKA.NS - Shree Renuka Sugars Ltd.",
    "REPCOHOME.NS - Repco Home Finance Ltd.",
    "RESPONIND.NS - Responsive Industries Ltd.",
    "RVNL.NS - Rail Vikas Nigam Ltd.",
    "SADBHAV.NS - Sadbhav Engineering Ltd.",
    "SHILPAMED.NS - Shilpa Medicare Ltd.",
    "SHK.NS - S H Kelkar and Company Ltd.",
    "SHOPERSTOP.NS - Shoppers Stop Ltd.",
    "SHRIRAMCIT.NS - Shriram City Union Finance Ltd.",
    "SIS.NS - Security and Intelligence Services (India) Ltd.",
    "SOBHA.NS - Sobha Ltd.",
    "SONATSOFTW.NS - Sonata Software Ltd.",
    "SPANDANA.NS - Spandana Sphoorty Financial Ltd.",
    "SPICEJET.NS - Spicejet Ltd.",
    "SRTRANSFIN.NS - Shriram Transport Finance Co. Ltd.",
    "STARCEMENT.NS - Star Cement Ltd.",
    "STRTECH.NS - Sterlite Technologies Ltd.",
    "SUNCLAYLTD.NS - Sundaram Clayton Ltd.",
    "SUNDARMFIN.NS - Sundaram Finance Ltd.",
    "SUNDRMFAST.NS - Sundram Fasteners Ltd.",
    "SWANENERGY.NS - Swan Energy Ltd.",
    "TAKE.NS - Take Solutions Ltd.",
    "TASTYBITE.NS - Tasty Bite Eatables Ltd.",
    "TATAMTRDVR.NS - Tata Motors Ltd DVR",
    "TATASTLBSL.NS - Tata Steel BSL Ltd.",
    "TCIEXP.NS - TCI Express Ltd.",
    "TCNSBRANDS.NS - TCNS Clothing Co. Ltd.",
    "TEAMLEASE.NS - Teamlease Services Ltd.",
    "TECHNOE.NS - Techno Electric & Engineering Company Ltd.",
    "THYROCARE.NS - Thyrocare Technologies Ltd.",
    "TRITURBINE.NS - Triveni Turbine Ltd.",
    "TTKPRESTIG.NS - TTK Prestige Ltd.",
    "TV18BRDCST.NS - TV18 Broadcast Ltd.",
    "TVTODAY.NS - TV Today Network Ltd.",
    "UCOBANK.NS - UCO Bank",
    "UFLEX.NS - UFLEX Ltd.",
    "UJJIVAN.NS - Ujjivan Financial Services Ltd.",
    "VAKRANGEE.NS - Vakrangee Ltd.",
    "VENKEYS.NS - Venky's (India) Ltd.",
    "VINATIORGA.NS - Vinati Organics Ltd.",
    "VMART.NS - V-Mart Retail Ltd.",
    "VSTIND.NS - VST Industries Ltd.",
    "VTL.NS - Vardhman Textiles Ltd.",
    "WABCOINDIA.NS - WABCO India Ltd.",
    "WELCORP.NS - Welspun Corp Ltd.",
    "WESTLIFE.NS - Westlife Development Ltd.",
    "WOCKPHARMA.NS - Wockhardt Ltd.",
    "CUSTOM / OTHER (Enter Custom Ticker)",
]